version: '3.4'

services:
  base64:
    image: base64
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8066"]
    ports:
      - 8066:8066
      - 5678:5678
